### ISSUE TITLE
UnCSS 

### ISSUE THREAD

**Issue by furzeface** [code-computerlove/code-ghost-theme#1]
I started using [gulp-uncss](https://www.npmjs.com/package/gulp-uncss) on static sites, could be useful.

:octocat:

**Comment by iamdarrenhall** [comment]
Could be, but it's not a static site. I know you can get static generators for ghost, so might be worth looking at in future.

**Comment by bmds** [comment]
The problem i've always had is that i would like these tools to generate a report that i can use to improve the base Sass rather than just stripping the styles.

**Comment by furzeface** [comment]
Ooh if there's not one out there it could be a good opportunity to write a task :smile: might get on it.
